# testing file for Travis
# https://travis-ci.org/neuropoly/spinalcordtoolbox

sudo: false  # To use travis container infrastructure

notifications:
  slack: neuropoly:YA3mt28aeHN3A0Iu7RvMFigK
    on_success:change
    on_failure:always

# this enables to avoid recompilation of dipy if it was already compiled previously
#cache:
#  directories:
#    - ${HOME}/.cache/pip

matrix:
  include:
    - os: linux  # list of Linux env: https://docs.travis-ci.com/user/reference/overview/
      name: "Ubuntu 18.04 (Bionic Beaver)"
      dist: bionic
    - os: osx  # list of OSX env: https://docs.travis-ci.com/user/reference/osx/
      name: "OSX 10.14 (Mojave)"
      osx_image: xcode11.2
    - os: osx
      name: "OSX 10.13 (High Sierra)"
      osx_image: xcode9.4

install:
  - |
    echo Installing SCT
    set -e  # Error build immediately if install script exits with non-zero
    yes | ASK_REPORT_QUESTION=false ./install_sct
    echo $?
    echo "... STATUS"
    PATH="$PATH:$PWD/bin"

before_script:
  - |
    echo *** CHECK PATH ***
    echo $PATH  # Make sure PATH includes sct/bin folder
    ls -lA bin  # Make sure all binaries and aliases are there
    sct_download_data -d sct_testing_data  # for tests
    source python/etc/profile.d/conda.sh  # to be able to call conda
    conda activate venv_sct  # reactivate conda for the pip install below
    python -c "import multiprocessing; print('There are', multiprocessing.cpu_count(), 'CPUs')"

script:
  - |
    echo "Test dmri_moco 2"
    pwd
    ls -l
    date # timestamp
    sct_testing -f sct_dmri_moco || true # this is needed to generate dmri/mask.nii
    export ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=1
    for i in `seq 100`; do
      echo `(cd sct_testing_data; sct_dmri_moco -i dmri/dmri.nii.gz -bvec dmri/bvecs.txt -g 3 -m dmri/mask.nii -ofolder dmri_test2 -r 1 2>/dev/null 1>&2; cat dmri_test2/moco_params.tsv | cut -f 1)`
    done |
    tee /dev/stderr |
    sort | uniq -c
    date # timestamp
