name: Tests

on:
  push:
    branches: [ master, release ]
  pull_request:
    branches: [ '*' ]
  schedule:
    - cron:  '0 11 * * *'

jobs:
  build:

    strategy:
      matrix:
        # The set of available runners on Github's infra is generous but
        # will never be complete: https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
        # to glue over this, we use docker images to emulate distros they don't have.
        # This isn't a perfect test but it's pretty good.
        # TODO: integrate WSL in this scheme too.
        os: [ubuntu-18.04, macos-10.15, windows-2019]
        z: [false]
        # To keep feedback fast, we only run a selection of common platforms in CI
        # The others run nightly, or 
        nightly: ${{ (github.event_name == 'schedule' || (github.event_name == 'push' && github.ref == 'refs/heads/release')) }}
        exclude:
          - z: false # does this cancel ALL?
        include:
          - name: ArchLinux
            os: ubuntu-18.04
            docker_image: archlinux
            p: ${{ (github.event_name == 'schedule' || (github.event_name == 'push' && github.ref == 'refs/heads/release')) }}
          - name: Debian Rolling Release
            os: ubuntu-18.04
            docker_image: debian:sid
            p: ${{ (github.event_name == 'schedule' || (github.event_name == 'push' && github.ref == 'refs/heads/release')) }}
          - name: Debian Testing
            os: ubuntu-18.04
            docker_image: debian:testing
            p: ${{ (github.event_name == 'schedule' || (github.event_name == 'push' && github.ref == 'refs/heads/release')) }}
          - name: Debian 10
            os: ubuntu-18.04
            docker_image: debian:10
            p: ${{ (github.event_name == 'schedule' || (github.event_name == 'push' && github.ref == 'refs/heads/release')) }}
          - name: Debian 9
            os: ubuntu-16.04 # use an older ubuntu's kernel to closer emulate the older Debian
            docker_image: debian:9
            p: ${{ (github.event_name == 'schedule' || (github.event_name == 'push' && github.ref == 'refs/heads/release')) }}
          - name: CentOS 8
            os: ubuntu-18.04
            docker_image: centos:8
            p: ${{ (github.event_name == 'schedule' || (github.event_name == 'push' && github.ref == 'refs/heads/release')) }}
          - name: CentOS 7
            os: ubuntu-16.04 # use an older ubuntu to closer emulate the older centos
            docker_image: centos:7
            p: ${{ (github.event_name == 'schedule' || (github.event_name == 'push' && github.ref == 'refs/heads/release')) }}
    name: ${{matrix.name || matrix.os}}
    runs-on: ${{matrix.os}}
    container: ${{matrix.docker_image}} # XXX if undefined this is ignored hopefully?
    steps:
    - uses: actions/checkout@v2
    - name: CI
      if: ${{ matrix.nightly }}
      run: |
        ./.ci.sh
